package com.THproject.tharidia_things.stamina;

public enum StaminaModifierType {
    MAX_STAMINA_FLAT,
    MAX_STAMINA_PERCENT,
    REGEN_RATE_FLAT,
    REGEN_RATE_PERCENT,
    CONSUMPTION_MULTIPLIER,
    ATTACK_COST_PERCENT,
    ROLL_COST_PERCENT,
    BOW_TENSION_COST_PERCENT,
    SPRINT_THRESHOLD_PERCENT,
    REGEN_DELAY_FLAT,
    BLOCK_REGEN_OVERRIDE
}

